### ISSUE TITLE
Can't import old kanji

### ISSUE THREAD

**Issue by hiphop4eva** [cubetastic33/sakubun#8] opened 2022-09-01 01:36 UTC
I'm on an android phone, and after I first download the file after pressing export on old site, there is a brief moment I can open the file (in the browser I assume). You can see it in the photo below, it says "aç" in the top right. The text looks bizarre, and when I import it nothing happens.
![Screenshot_20220901-042822_Chrome](https://user-images.githubusercontent.com/99391376/187813680-e0ce1964-e168-4f0b-b4ff-ade6f324970b.jpg)
![Screenshot_20220901-042833_Chrome](https://user-images.githubusercontent.com/99391376/187813684-dceea385-9a0c-4e70-8b92-a87f616fc3d0.jpg)

I also tried to open the file directly in the files, but it says my phone can't open it.

![Screenshot_20220901-042846_My Files](https://user-images.githubusercontent.com/99391376/187813735-43251477-d91e-4f28-9d48-93281f481bbd.jpg)

**Comment by cubetastic33** [comment] 2022-09-01 03:43
What browser is this? I can't seem to reproduce the issue, but I can add an option to copy paste the kanji instead.

**Comment by cubetastic33** [comment] 2022-09-01 04:16
I've added a `Copy Kanji` button now - you should be able to use that to paste your kanji list into the text box in the new URL, and transfer your kanji list.

**Comment by hiphop4eva** [comment] 2022-09-01 16:22
The browser is google chrome, on mobile. In any case, the copy kanjı button worked :)
Thanks for the effort.

**Comment by cubetastic33** [comment] 2022-09-01 16:35
I think it might be because your browser is outdated, but I'm glad you were able to transfer your kanji list. Closing this issue now.

**Closed as completed by cubetastic33** 2022-09-01 16:35 UTC
